Add resource
CloudBytes-Academy/CloudBytes.dev pull request #126
Opened 2022-08-08 20:57 UTC by hdadhich01

Added a resource that uses the guide amongst other tools to set up a complete development environment.

2022-08-09 11:31 UTC, rehanhaider commented on content/articles/99999980-upgrade-python-on-linux.md
> +You can also learn how to [set up a WSL terminal](https://github.com/hdadhich01/wsl-terminal) to have a full-fledged Python development environment.
I don't think this is relevant and specific enough to the article scope and should not be included.

2022-08-09 11:32 UTC, rehanhaider requested changes
Please remove non-article scope specific instructions.

2022-08-09 11:32 UTC, rehanhaider commented on content/articles/99999980-upgrade-python-on-linux.md
> +Now you can run your files with `py` or `python`. To help you skip the hassle in virtual environment setup and package management, consider using [PDM](https://pdm.fming.dev/latest/).
I don't think this is relevant and specific enough to the article scope and should not be included.

2022-08-11 19:17 UTC, hdadhich01 commented
The current setup removes the ability to run `sudo add-apt-repository` because we removed and reinstalled `python3-apt`. I couldn't find a way to work around this.

2023-10-06 18:57 UTC, rehanhaider commented
Closing due to inactivity.

2023-10-06 18:57 UTC, closed without merging